keywords:
  perpetual title: Perpetual Title
  triple crown senior living: Triple Crown Senior Living
  triple crown: Triple Crown Senior Living
  triplecrownsl: Triple Crown Senior Living
  direct gp investments: Direct GP Investments
  direct gp: Direct GP Investments
  plowshares capital: Plowshares Capital
  plowshares: Plowshares Capital
  blockchange louisville: BlockChange Louisville
  blockchange: BlockChange Louisville
  chip-shot: Chip-Shot
  chip shot: Chip-Shot
  escrowx: EscrowX
  escrow x: EscrowX
  tokenization initiatives: Tokenization Initiatives
  tokenization: Tokenization Initiatives
  equine blocks: Equine Blocks
  strategic advisory positions: Strategic Advisory Positions
  strategic advisory: Strategic Advisory Positions
  louisville low voltage: Louisville Low Voltage
  louisville voltage: Louisville Low Voltage
  domidocs: DomiDocs
  sapphire fiduciary: Sapphire Fiduciary
  assisted living transitions: Assisted Living Transitions
  proptech lab: PropTech Lab
  proptech: PropTech Lab
  astrella fund: Astrella Fund LLC
  astrella: Astrella Fund LLC
  riverbend: River Bend Portfolio
  river bend: River Bend Portfolio

sender_domains:
  perpetualtitle.com: Perpetual Title
  chipridge.com: Chip Ridge
  triplecrownsl.com: Triple Crown Senior Living
  plowsharescapital.com: Plowshares Capital
  dentonfloyd.com: Direct GP Investments
  themariangroup.com: Strategic Advisory Positions
  firstam.com: Perpetual Title
  dmlo.com: Plowshares Capital
  louisvillelowvoltage.com: Louisville Low Voltage
  channelmarkeradvisors.com: Plowshares Capital
  fmdlegal.com: Direct GP Investments
